Revert "Drop results if mapping runs and allow to clear results from runtime"
This reverts commit e6700ce9dd9b16f4116e41a1798acde8838b7a65.

Drops to early.

proj_item, = runtime.results().synapse_routing.synapses().find(proj)
ValueError: need more than 0 values to unpack

Change-Id: I658d2c8b98dfbd335987f642b1dbfa8ea7bdeee5